# Site settings
title: Zixiao Wang
email: wang5586@umn.edu
description: Personal Site
baseurl: "/PersonalSite" # the subpath of your site, e.g. /blog/

url:  # the base hostname & protocol for your site
twitter_username: 
github_username:  ZTSean

# Build settings
markdown: kramdown
